### PR TITLE
Fixed bug for Issue #50.

### PR DESCRIPTION
**Pull request by dwerder**
@Conzar wrote:

By setting the provider on the server worked for Ubuntu 12.04, 14.04,
and 15.04.  I was unable to get 10.04 working (there were some problems
outside the scope of this issue with the code that 10.04 has).

However, I ran into a new issue with 15.04.  The following bug report
best describes the problem:

https://bugs.launchpad.net/ubuntu/+source/nfs-utils/+bug/1428961

Essentially, idmapd no longer as an init script and therefore fails. The
nfs-server init script manages idmapd so I used a case statement to
remove this functionality from Ubuntu 15.04 and later versions.

Finially, I added a vagrant directory that contains the testing
framework that I used to manually test all of the supported version
(10.04, 12.04, 14.04, and 15.04).  I had to modify the tests/init.pp to
test both the server and client.

### CODE REVIEW

**Comment by dwerder** [comment]
Travis-ci failes, because some spec test for Ubuntu expect idmap service to be stopped or started. If that test get fixed everything is fine.

**Comment by Conzar** [comment]
I created the feature branch from the develop branch.  Sorry that I messed up the pull request and thank you for fixing it.  I haven't learned the rspec testing so it might take me a while to look into the testing.

**Comment by dwerder** [comment]
Sorry for the late response. There is a check failing with idmap. If that check get fixed everything is ready to be merged.

**Comment by dwerder** [comment]
Stale and closed

**Pull request closed without merging**
