### PR TITLE
allow client mounts to be defined in Hiera

### PR DESCRIPTION
**Pull request by madddi**

### CODE REVIEW

**Comment by dwerder** [comment]
Why sould there be a new parameter? To archive what you want you can simply make a hiera lookup in your main manifest:

```puppet
node bla {
   create_resources(nfs::client::mount, hiera(my::hier:vatiable) )
}

**Comment by madddi** [comment]
Of course I could create the resources in my main manifest. However, `nfs::server::exports` enables me to provide exports via Hiera, while there is no such feature for client mounts.

**Comment by jcpunk** [comment]
I am also in this feature is it will allow me to define mounts via my ENC.

**Comment by dwerder** [comment]
Can you please reopen this PR against develop branch. Maybe a rpesc test and update of README would also be fine.

**Pull request closed without merging**
